export const mockDataBlogsPost = [
  {
    uuid: "d690c23a-17a5-4d06-9e08-7c2768b9323a",
    category: "Programming",
    title: "Introduction to Python",
    description: "An overview of the Python programming language.",
    content: "Python is a versatile and beginner-friendly programming...",
    tags: ["Python", "Programming"],
    createdDate: "2023-08-15",
    slug: "introduction-to-python",
    image: "https://i.postimg.cc/hGfFtdTQ/pexels-pixabay-265087.jpg",
    author: "lavdev",
  },
  {
    uuid: "a8c91c18-2f6a-4f3f-ae51-9b7540faa46b",
    category: "Programming",
    title: "Java Fundamentals",
    description: "Exploring the core concepts of Java programming.",
    content: "Java is an object-oriented programming language...",
    tags: ["Java", "Programming"],
    createdDate: "2023-08-16",
    slug: "java-fundamentals",
    image: "https://i.postimg.cc/hGfFtdTQ/pexels-pixabay-265087.jpg",
    author: "lavdev",
  },
  {
    uuid: "f2e0b9d2-2b53-45d2-884d-8d96c01c4397",
    category: "Programming",
    title: "Getting Started with JavaScript",
    description: "A beginner's guide to JavaScript programming.",
    content: "JavaScript is a scripting language commonly used...",
    tags: ["JavaScript", "Web Development"],
    createdDate: "2023-08-17",
    slug: "getting-started-with-javascript",
    image: "https://i.postimg.cc/hGfFtdTQ/pexels-pixabay-265087.jpg",
    author: "lavdev",
  },
  {
    uuid: "8793e06a-72ed-4767-9e7b-2d35437c95dd",
    category: "Programming",
    title: "Fundamentals of C++",
    description: "Exploring the basics of C++ programming language.",
    content: "C++ is a powerful and widely used programming language...",
    tags: ["C++", "Programming"],
    createdDate: "2023-08-18",
    slug: "fundamentals-of-cplusplus",
    image: "https://i.postimg.cc/hGfFtdTQ/pexels-pixabay-265087.jpg",
    author: "lavdev",
  },
  {
    uuid: "5ac5d41b-21f4-4a29-bd04-1e2d01a1a763",
    category: "Web Development",
    title: "HTML5 and CSS3 Essentials",
    description: "An introduction to HTML5 and CSS3 for web development.",
    content: "HTML5 and CSS3 are the building blocks of modern web...",
    tags: ["HTML5", "CSS3", "Web Development"],
    createdDate: "2023-08-19",
    slug: "html5-and-css3-essentials",
    image: "https://i.postimg.cc/hGfFtdTQ/pexels-pixabay-265087.jpg",
    author: "lavdev",
  },
  {
    uuid: "6e309c4b-891d-43fe-9834-88232007ac7c",
    category: "Web Development",
    title: "Mastering React: A Comprehensive Guide",
    description: "A deep dive into React.js for building interactive UIs.",
    content: "React is a popular JavaScript library for building user...",
    tags: ["React", "JavaScript", "Web Development"],
    createdDate: "2023-08-20",
    slug: "mastering-react-comprehensive-guide",
    image: "https://i.postimg.cc/hGfFtdTQ/pexels-pixabay-265087.jpg",
    author: "lavdev",
  },
  {
    uuid: "4c3f739c-c0e4-4c6b-8a49-8d7d123521e2",
    category: "Machine Learning",
    title: "Introduction to Neural Networks",
    description:
      "Understanding the basics of neural networks and their applications.",
    content: "Neural networks are a fundamental concept in machine learning...",
    tags: ["Neural Networks", "Machine Learning"],
    createdDate: "2023-08-21",
    slug: "introduction-to-neural-networks",
    image: "https://i.postimg.cc/hGfFtdTQ/pexels-pixabay-265087.jpg",
    author: "lavdev",
  },
  // Continue with 3 more blog posts...
];
